CREATE TABLE xxkpmg_accounts_tbl_bnk (
    account_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      NUMBER NOT NULL,
    IFCS_code        VARCHAR2(11) NOT NULL,
    branch_name      VARCHAR2(100) NOT NULL,
    account_type     VARCHAR2(20) CHECK (account_type IN ('SAVINGS', 'CURRENT', 'LOAN','FIXED DEPOSIT', 'RECURRING DEPOSIT')) NOT NULL,
    balance          NUMBER(15,2) DEFAULT 0 CHECK (balance >= 0),
    status           VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','FROZEN','CLOSED')),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES xxkpmg_customers_tbl_bnk(customer_id)
);


SELECT * FROM USER_TABLES WHERE TABLE_NAME LIKE 'XXKPMG_%';

-- DROP TABLE XXKPMG_ACCOUNTS_TBL_BNK CASCADE CONSTRAINTS;
-- DROP TABLE XXKPMG_CUSTOMERS_TBL_BNK CASCADE CONSTRAINTS;
-- DROP TABLE XXKPMG_TRANSACTIONS_TBL_BNK CASCADE CONSTRAINTS;
-- DROP TABLE XXKPMG_TRANSFERS_TBL_BNK CASCADE CONSTRAINTS;
ALTER TABLE xxkpmg_accounts_tbl_bnk RENAME COLUMN IFCS_code TO IFSC_code;

SELECT * FROM XXKPMG_CUSTOMERS_TBL_BNK;

INSERT INTO XXKPMG_ACCOUNTS_TBL_BNK (customer_id, IFSC_code, branch_name, account_type, balance, status) VALUES (1, 'KPMG0001', 'KPMG Main Branch', 'SAVINGS', 5000.00, 'ACTIVE'); commit;
INSERT INTO XXKPMG_ACCOUNTS_TBL_BNK (customer_id, IFSC_code, branch_name, account_type, balance, status) VALUES (1, 'KPMG0002', 'KPMG West Branch', 'CURRENT', 15000.00, 'ACTIVE'); commit;
INSERT INTO XXKPMG_ACCOUNTS_TBL_BNK (customer_id, IFSC_code, branch_name, account_type, balance, status) VALUES (2, 'KPMG0001', 'KPMG Main Branch', 'SAVINGS', 8000.00, 'ACTIVE'); commit;
INSERT INTO XXKPMG_ACCOUNTS_TBL_BNK (customer_id, IFSC_code, branch_name, account_type, balance, status) VALUES (3, 'KPMG0003', 'KPMG East Branch', 'SAVINGS', 20000.00, 'ACTIVE');
COMMIT;

SELECT  * FROM xxkpmg_accounts_tbl_bnk;

SELECT a.full_name, xatb.*
  FROM XXKPMG_ACCOUNTS_TBL_BNK xatb, XXKPMG_CUSTOMERS_TBL_BNK a
  WHERE a.customer_id = xatb.customer_id;
