CREATE TABLE xxkpmg_customers_tbl_bnk (
    customer_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR2(100) NOT NULL,
    email            VARCHAR2(100) UNIQUE NOT NULL,
    phone            VARCHAR2(20),
    address          VARCHAR2(255),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP 
);
BEGIN
INSERT INTO xxkpmg_customers_tbl_bnk (full_name, email, phone, address)VALUES('ARPAN KARMAKAR', 'arpankarmakar@kpmg.com', '9064625510', 'Kolkata, India');
INSERT INTO xxkpmg_customers_tbl_bnk (full_name, email, phone, address)VALUES('SIDDHARTHA MUKHERJEE', 'siddhartham3@kpmg.com', '6289368650', 'Kolkata, India');
INSERT INTO xxkpmg_customers_tbl_bnk (full_name, email, phone, address)VALUES('AYAN CHAKRABORTY', 'ayanchakraborty3@kpmg.com', '9083689585', 'Kolkata, India');
COMMIT;
END;
/

SELECT * FROM xxkpmg_customers_tbl_bnk;

-- CREATE USER application_user IDENTIFIED BY sys123;
-- GRANT CONNECT, RESOURCE TO application_user;
-- GRANT CREATE SESSION TO application_user;
-- GRANT CREATE TABLE TO application_user;
-- GRANT CREATE VIEW TO application_user;
-- GRANT CREATE SEQUENCE TO application_user;
-- GRANT CREATE PROCEDURE TO application_user;
-- GRANT CREATE TRIGGER TO application_user;
ALTER USER application_user QUOTA UNLIMITED ON USERS;
commit;
-- GRANT INSERT, UPDATE, DELETE TO application_user;

-- BEGIN
--    FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'SCHEMA_NAME') LOOP
--       EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA_NAME.' 
--                         || t.table_name || ' TO application_user';
--    END LOOP;
-- END;
-- /