CREATE  TABLE   xxkpmg_authentication_tbl_bnk (
    auth_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    NUMBER NOT NULL,
    password       VARCHAR2(255) NOT NULL,
    email          VARCHAR2(100) UNIQUE NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_customer_auth
        FOREIGN KEY (customer_id)
        REFERENCES xxkpmg_customers_tbl_bnk(customer_id)
        ON DELETE CASCADE
);

SELECT * FROM xxkpmg_customers_tbl_bnk;

INSERT INTO xxkpmg_authentication_tbl_bnk (customer_id, password, email) VALUES (1, 'password123', 'arpankarmakar@kpmg.com');   
INSERT INTO xxkpmg_authentication_tbl_bnk (customer_id, password, email) VALUES (2, 'password456', 'siddhartham3@kpmg.com');   
INSERT INTO xxkpmg_authentication_tbl_bnk (customer_id, password, email) VALUES (3, 'password789', 'ayanchakraborty3@kpmg.com');
COMMIT;


SELECT * FROM xxkpmg_authentication_tbl_bnk;