CREATE TABLE xxkpmg_transactions_tbl_bnk (
    transaction_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       NUMBER NOT NULL,
    type             VARCHAR2(20) CHECK (type IN ('DEPOSIT','WITHDRAW','TRANSFER_IN','TRANSFER_OUT')),
    amount           NUMBER(15,2) NOT NULL CHECK (amount > 0),
    description      VARCHAR2(255),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES xxkpmg_accounts_tbl_bnk(account_id)
);