CREATE TABLE xxkpmg_transactions_tbl_bnk (
    transaction_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       NUMBER NOT NULL,
    transaction_type VARCHAR2(20),
    status           VARCHAR2(20) CHECK (status IN ('PENDING','COMPLETED','FAILED', 'SUCCESS')),
    amount           NUMBER(15,2) NOT NULL CHECK (amount > 0),
    description      VARCHAR2(255),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    related_account  NUMBER,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES xxkpmg_accounts_tbl_bnk(account_id)
);

DROP TABLE xxkpmg_transactions_tbl_bnk;

SELECT * FROM xxkpmg_transactions_tbl_bnk;


ALTER TABLE xxkpmg_transactions_tbl_bnk 
  ADD transfer_id VARCHAR2(50);



  SELECT xxkpmg_transactions_seq.NEXTVAL AS txn_id FROM dual;