CREATE TABLE xxkpmg_transfers_tbl_bnk (
    transfer_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id  NUMBER NOT NULL,
    to_account_id    NUMBER NOT NULL,
    amount           NUMBER(15,2) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'SUCCESS' CHECK (status IN ('SUCCESS','FAILED')),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_from_account FOREIGN KEY (from_account_id) REFERENCES xxkpmg_accounts_tbl_bnk(account_id),
    CONSTRAINT fk_to_account   FOREIGN KEY (to_account_id) REFERENCES xxkpmg_accounts_tbl_bnk(account_id)
);